//#define ADSGouraud
//#define ADSPhong
//#define DiffuseLight
//#define Dissolve
//#define FlatShader
//#define LitTexture
//#define ProvokingVertex
//#define ShadedTriangle
//#define TexturedTriangle
//#define ToonShader
#define Triangle